apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  mysql-root-password: "root"
  mysql-user: "ecommerce_user"
  mysql-password: "ecommerce_pass"
  redis-password: "ecommerce_redis_pass"
