package com.mustapha.ecommerce.order.domain.event;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;

import com.mustapha.ecommerce.order.domain.model.valueobject.CustomerId;
import com.mustapha.ecommerce.order.domain.model.valueobject.Money;
import com.mustapha.ecommerce.order.domain.model.valueobject.OrderId;

import static org.junit.jupiter.api.Assertions.*;

/**
 * PROOF: Records provide ALL the same functionality as final classes
 * This test verifies that record auto-generation works correctly
 */
class RecordFunctionalityTest {
    
    @Test
    void record_provides_getters() {
        // Given
        OrderId orderId = OrderId.generate();
        CustomerId customerId = CustomerId.generate();
        Money amount = new Money(100);
        
        // When
        OrderPlacedEvent event = new OrderPlacedEvent(orderId, customerId, amount);
        
        // Then - ALL getters work (auto-generated by record)
        assertNotNull(event.eventId());         // ✅ Auto-generated getter
        assertEquals(orderId, event.orderId()); // ✅ Auto-generated getter
        assertEquals(customerId, event.customerId()); // ✅ Auto-generated getter
        assertEquals(amount, event.totalAmount()); // ✅ Auto-generated getter
        assertNotNull(event.occurredAt());      // ✅ Auto-generated getter
    }
    
    @Test
    void record_provides_equals_and_hashCode() {
        // Given - same event ID means same event
        String eventId = "same-id";
        OrderId orderId = OrderId.generate();
        CustomerId customerId = CustomerId.generate();
        Money amount = new Money(100);
        LocalDateTime time = LocalDateTime.now();
        
        OrderPlacedEvent event1 = new OrderPlacedEvent(eventId, orderId, customerId, amount, time);
        OrderPlacedEvent event2 = new OrderPlacedEvent(eventId, orderId, customerId, amount, time);
        
        // Then - equals() and hashCode() work (auto-generated by record)
        assertEquals(event1, event2);           // ✅ Auto-generated equals()
        assertEquals(event1.hashCode(), event2.hashCode()); // ✅ Auto-generated hashCode()
    }
    
    @Test
    void record_provides_toString() {
        // Given
        OrderId orderId = OrderId.generate();
        CustomerId customerId = CustomerId.generate();
        Money amount = new Money(100);
        
        // When
        OrderPlacedEvent event = new OrderPlacedEvent(orderId, customerId, amount);
        String result = event.toString();
        
        // Then - toString() shows all fields (auto-generated by record)
        assertNotNull(result);
        assertTrue(result.contains("OrderPlacedEvent")); // ✅ Auto-generated toString()
        assertTrue(result.contains(orderId.toString()));
        assertTrue(result.contains(customerId.toString()));
    }
    
    @Test
    void record_is_immutable() {
        // Given
        OrderId orderId = OrderId.generate();
        CustomerId customerId = CustomerId.generate();
        Money amount = new Money(100);
        OrderPlacedEvent event = new OrderPlacedEvent(orderId, customerId, amount);
        
        // Then - NO setters exist (record is immutable by design)
        // event.setOrderId(...) // ❌ Does NOT compile - no setters!
        // event.eventId = "new"; // ❌ Does NOT compile - fields are final!
        
        // ✅ Can only read, never modify
        assertNotNull(event.orderId());
    }
    
    @Test
    void record_validates_in_compact_constructor() {
        // Given
        OrderId orderId = OrderId.generate();
        CustomerId customerId = CustomerId.generate();
        Money amount = new Money(100);
        
        // Then - validation still works (compact constructor)
        assertThrows(IllegalArgumentException.class, () -> {
            new OrderPlacedEvent(null, orderId, customerId, amount, LocalDateTime.now());
        }, "Event ID cannot be null"); // ✅ Validation preserved!
        
        assertThrows(IllegalArgumentException.class, () -> {
            new OrderPlacedEvent("id", null, customerId, amount, LocalDateTime.now());
        }, "Order ID cannot be null"); // ✅ Validation preserved!
    }
    
    @Test
    void record_has_convenience_constructor() {
        // When - convenience constructor auto-generates ID and timestamp
        OrderPlacedEvent event = new OrderPlacedEvent(
            OrderId.generate(), 
            CustomerId.generate(), 
            new Money(100)
        );
        
        // Then - ID and timestamp are set automatically
        assertNotNull(event.eventId());    // ✅ Convenience constructor works!
        assertNotNull(event.occurredAt()); // ✅ Convenience constructor works!
    }
    
    @Test
    void record_implements_DomainEvent_interface() {
        // Given
        OrderPlacedEvent event = new OrderPlacedEvent(
            OrderId.generate(), 
            CustomerId.generate(), 
            new Money(100)
        );
        
        // Then - implements DomainEvent interface
        assertNotNull(event.getEventId());    // ✅ Interface method
        assertNotNull(event.getOccurredAt()); // ✅ Interface method
    }
}
